// <auto-generated />
namespace GpxViewer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemovePropertiesFromPoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovePropertiesFromPoint));
        
        string IMigrationMetadata.Id
        {
            get { return "201306071421232_RemovePropertiesFromPoint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
